version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-pipdevs/app}
    links:
      - mongo
    environment:
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_DB=app
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
    ports:
      - "8080:8080"
      - "8090:8090"

  mongo:
    image: mongo:latest
