version: '3.3'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-pipservices/app}
    environment:
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
    ports:
      - "8080:8080"
      - "8090:8090"
